apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-app-0121
    app.kubernetes.io/component: weather-app-0121
    app.kubernetes.io/instance: weather-app-0121
    app.openshift.io/runtime: jboss
  name: weather-app-0121
  namespace: tak-work
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.openshift.io/runtime: jboss
      deployment: weather-app-0121
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app.openshift.io/runtime: jboss
        deployment: weather-app-0121
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/tak-work/weather-app-0121@sha256:226c4a2fe086535eb6524281b0740959d8bbed98d0671b7e8b30d60bf3fe66c4
        imagePullPolicy: IfNotPresent
        name: weather-app-0121
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        envFrom:
          - configMapRef:
              name: ds-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mycredstore-volume
        secret:
          secretName: mycredstore
